# Generated by Django 5.0.1 on 2024-01-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sensor', models.CharField(max_length=50)),
                ('type_sensor', models.CharField(max_length=50)),
                ('value_sensor', models.FloatField()),
                ('ubication_sensor', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
