# Generated by Django 5.0.1 on 2024-01-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_actuator', models.CharField(max_length=50)),
                ('type_actuator', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('ubication_actuator', models.CharField(max_length=50)),
            ],
        ),
    ]
