# Generated by Django 5.0.1 on 2024-01-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_actuator'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='value_actuator',
            field=models.BooleanField(default=False),
        ),
    ]
