# Generated by Django 5.0.1 on 2024-01-10 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_actuator_value_actuator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_controller', models.CharField(max_length=50)),
                ('logical_controller', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Domotic_central',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_domotic_central', models.CharField(max_length=20)),
                ('interface_domotic_central', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission_medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_transmission_medium', models.CharField(max_length=30)),
                ('type_transmission_medium', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=30)),
                ('password_user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ControllerActuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actuator')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.controller')),
            ],
        ),
        migrations.CreateModel(
            name='ControllerSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.controller')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='CentralController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.controller')),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.domotic_central')),
            ],
        ),
        migrations.CreateModel(
            name='SensorActuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actuator')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='MediumController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.controller')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transmission_medium')),
            ],
        ),
        migrations.CreateModel(
            name='UserCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50)),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.domotic_central')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
