# Generated by Django 5.0.1 on 2024-01-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_controller_domotic_central_transmission_medium_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercentral',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_central', to='api.user'),
        ),
    ]
